services:
  #1 Database Layer
  postgres-db:
    image: timescale/timescaledb-ha:pg16
    container_name: coffeebase_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: coffeebase_dev
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
